--- 
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: I want to create file
    file:
     path: /home/ubuntu/dbfile1
     state: touch
    when: ansible_os_family=="Debian"
  
  - name: I want to create file
    file:
     path: /home/redhat/dbfile2
     state: touch
    when: ansible_os_family=="RedHat"
  