--- 
- hosts: 172.31.89.253
  become: yes
  tasks:
  - name: i want to execute linux command directly.
    command: hostname -f 
    register: myfirstresult

  - name: I want to display first task result
    debug:
       msg: "{{myfirstresult}}"