--- 
- hosts: 172.31.83.34
  become: yes 
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
     name: apache2
     state: present

  - name: I want to copy indexfile into node side
    template:
         src:  myindex.j2
         dest: /var/www/html/index.html
  
  - name: downlaod remote files remote files
    get_url:
        url: https://get.jenkins.io/war-stable/2.319.1/jenkins.war
        dest: /home/ubuntu/jenkins.war
        force_basic_auth: yes