--- 
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
   -  name: i want to install apache2 on only ubuntu nodes
      apt:
        name: "{{mywebserverpackforubuntu}}"
        state: present
      when: ansible_os_family=="Debian"

   -  name: i want to start apache2 on only ubuntu nodes
      service:
        name: "{{mywebserverpackforubuntu}}"
        state: started
      when: ansible_os_family=="Debian"

   -  name: i want to install httpd on only RedHat nodes
      yum:
        name: "{{mywebserverpackforredhat}}"
        state: present
      when: ansible_os_family=="RedHat"

   -  name: i want to start httpd on only Redhat nodes
      service:
        name: "{{mywebserverpackforredhat}}"
        state: started
      when: ansible_os_family=="RedHat"
  