--- 
- hosts: all 
  become: yes
  gather_facts: no
  tasks:
   -  name: i want to install apache2
      apt:
        name: apache2
        state: present
   -  name: i want to uninstall apache2
      apt:
        name: apache2
        state: absent