--- 
- hosts: mywebservers 
  become: yes 
  gather_facts: yes 
  tasks:
   -  name: i want to install apache server on ubuntu nodes
      apt:
       name: "{{mywebserverpackforubuntu}}"
       state: present
      when: ansible_os_family=="Debian"

   -  name: i want to restart my ubuntu server
      service:
        name: "{{mywebserverpackforubuntu}}"
        state: started
      when: ansible_os_family=="Debian"

   -  name: i want to install apache server on redhat nodes
      apt:
       name: "{{mywebserverpackforredhat}}"
       state: present
       when: ansible_os_family=="RedHat"

   -  name: i want to restart my ubuntu server
      service:
       name: "{{mywebserverpackforredhat}}"
       state: started
      when: ansible_os_family=="RedHat"