--- 
- hosts: 172.31.10.44 
  become: yes
  tasks:
  - name: Install webserver on ubuntu
    apt:
      name: apache2
      state: present

  - name: Start webserver
    apt: 
     name: apache2
     state: started