--- 
- hosts: 172.31.0.208
  become: yes
  tasks:
  - name: Install webserver on ubuntu
    apt:
      name: apache2
      state: present

  - name: Start webserver
    service: 
     name: apache2
     state: started

  - name: i want to create a file
    file: 
       path: /home/ubuntu/file1
       state: touch