--- 
- hosts: mywebservers
  tasks:
  - name: i want to install apache server
    apt:
     name: apache2
     state: present

  - name: i want to start server
    service:
     name: apache2
     state: started