--- 
- hosts: All 
  become: yes 
  gathering_facts: yes
  tasks: 
  - name: I want to install apche2 on ubuntu server
    apt:
     name: apache2
     state: present 
     when: ansible_os_family=="Debian"

  - name: I want to restart my apache server
    service:
     name: apache2
     state: started 
     when: ansible_os_family=="Debian"

  - name: I want to install httpd on linux server
    apt:
     name: httpd
     state: present 
     when: ansible_os_family=="RedHat"

  - name: I want to restart my Linux server
    service:
     name: httpd 
     state: started
     when: ansible_os_family=="RedHat"


