---
# tasks file for mytomcat8role
- include_tasks: InstallJava.yml
- include_tasks: CreateTomcatUser.yml
- include_tasks: InstallTomcat.yml
- include_tasks: UpdatePermissions.yml
- include_tasks: systemdServiceFile.yml
- include_tasks: starttomcat.yml
#- include-tasks: TomcatWebManagement.yml