--- 
- name: copy tomcat user file into node side.
  template:
       src: templates/mytomuser.j2
       dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy manager context file into node side.
  template:
       src: templates/mymanagercontext.j2
       dest: /opt/tomcat/webapps/manager/META-INF/context.xml


- name: copy host context file into node side.
  templates:
        src: templates/hostcontext.j2
        dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml